sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t saritah/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true saritah/docker-react npm run test
